version: '2'
services:

  php:
    image: php:7-apache
    container_name: test_apache
    restart: always
    volumes:
      - ./html/:/var/www/html
    ports:
      - 80:80
  mysql:
    image: mysql:5.7
    container_name: test_mysql
    ports:
      - 3308:3306
    volumes:
      - "./data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 123132123
      MYSQL_DATABASE: testdb
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8000:80
    environment:
      PMA_PASSWORD: 123132123
      PMA_USER: root
      PMA_HOSTS: mysql